package mess.wkb.cm.code.mapper;

import mess.wkb.cm.code.vo.CmAttendance;

public interface CmAttendanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_attendance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_attendance
     *
     * @mbg.generated
     */
    int insert(CmAttendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_attendance
     *
     * @mbg.generated
     */
    int insertSelective(CmAttendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_attendance
     *
     * @mbg.generated
     */
    CmAttendance selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_attendance
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmAttendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_attendance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmAttendance record);
}