package mess.wkb.cm.code.mapper;

import mess.wkb.cm.code.vo.CmDepartmentApply;

public interface CmDepartmentApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_department_apply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_department_apply
     *
     * @mbg.generated
     */
    int insert(CmDepartmentApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_department_apply
     *
     * @mbg.generated
     */
    int insertSelective(CmDepartmentApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_department_apply
     *
     * @mbg.generated
     */
    CmDepartmentApply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_department_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmDepartmentApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_department_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmDepartmentApply record);
}