package mess.wkb.cm.code.mapper;

import mess.wkb.cm.code.vo.CmDepartment;

public interface CmDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_department
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_department
     *
     * @mbg.generated
     */
    int insert(CmDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_department
     *
     * @mbg.generated
     */
    int insertSelective(CmDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_department
     *
     * @mbg.generated
     */
    CmDepartment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_department
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_department
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmDepartment record);
}