package mess.wkb.cm.code.mapper;

import mess.wkb.cm.code.vo.CmPayment;

public interface CmPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_payment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_payment
     *
     * @mbg.generated
     */
    int insert(CmPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_payment
     *
     * @mbg.generated
     */
    int insertSelective(CmPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_payment
     *
     * @mbg.generated
     */
    CmPayment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmPayment record);
}