package mess.wkb.cm.code.mapper;

import mess.wkb.cm.code.vo.CmPaymentRecord;

public interface CmPaymentRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_payment_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_payment_record
     *
     * @mbg.generated
     */
    int insert(CmPaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_payment_record
     *
     * @mbg.generated
     */
    int insertSelective(CmPaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_payment_record
     *
     * @mbg.generated
     */
    CmPaymentRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_payment_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmPaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_payment_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmPaymentRecord record);
}