package mess.wkb.cm.code.mapper;

import mess.wkb.cm.code.vo.CmPower;

public interface CmPowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_power
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_power
     *
     * @mbg.generated
     */
    int insert(CmPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_power
     *
     * @mbg.generated
     */
    int insertSelective(CmPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_power
     *
     * @mbg.generated
     */
    CmPower selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_power
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_power
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmPower record);
}