package mess.wkb.cm.code.mapper;

import mess.wkb.cm.code.vo.CmRole;

public interface CmRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_role
     *
     * @mbg.generated
     */
    int insert(CmRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_role
     *
     * @mbg.generated
     */
    int insertSelective(CmRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_role
     *
     * @mbg.generated
     */
    CmRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmRole record);
}