package mess.wkb.cm.code.mapper;

import mess.wkb.cm.code.vo.CmScheme;

public interface CmSchemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_scheme
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_scheme
     *
     * @mbg.generated
     */
    int insert(CmScheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_scheme
     *
     * @mbg.generated
     */
    int insertSelective(CmScheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_scheme
     *
     * @mbg.generated
     */
    CmScheme selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_scheme
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmScheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_scheme
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmScheme record);
}