package mess.wkb.cm.code.mapper;

import mess.wkb.cm.code.vo.CmStudent;

public interface CmStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_student
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_student
     *
     * @mbg.generated
     */
    int insert(CmStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_student
     *
     * @mbg.generated
     */
    int insertSelective(CmStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_student
     *
     * @mbg.generated
     */
    CmStudent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_student
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_student
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmStudent record);
}