package mess.wkb.cm.code.mapper;

import mess.wkb.cm.code.vo.CmWorkSummary;

public interface CmWorkSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_work_summary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_work_summary
     *
     * @mbg.generated
     */
    int insert(CmWorkSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_work_summary
     *
     * @mbg.generated
     */
    int insertSelective(CmWorkSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_work_summary
     *
     * @mbg.generated
     */
    CmWorkSummary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_work_summary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmWorkSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_work_summary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmWorkSummary record);
}