package mess.wkb.cm.code.vo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cm_attendance_record
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CmAttendanceRecord implements Serializable {
    /**
     *
     */
    private Long id;

    /**
     *   签到时间
     */
    private Date signTime;

    /**
     *   所属部门
     */
    private String departmentId;

    /**
     *   发起人
     */
    private String userName;

    /**
     *   状态
     */
    private String state;

    /**
     *   活动id
     */
    private Long attendanceId;

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_attendance_record.id
     *
     * @return the value of cm_attendance_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_attendance_record.id
     *
     * @param id the value for cm_attendance_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_attendance_record.sign_time
     *
     * @return the value of cm_attendance_record.sign_time
     *
     * @mbg.generated
     */
    public Date getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_attendance_record.sign_time
     *
     * @param signTime the value for cm_attendance_record.sign_time
     *
     * @mbg.generated
     */
    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_attendance_record.department_id
     *
     * @return the value of cm_attendance_record.department_id
     *
     * @mbg.generated
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_attendance_record.department_id
     *
     * @param departmentId the value for cm_attendance_record.department_id
     *
     * @mbg.generated
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_attendance_record.user_name
     *
     * @return the value of cm_attendance_record.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_attendance_record.user_name
     *
     * @param userName the value for cm_attendance_record.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_attendance_record.state
     *
     * @return the value of cm_attendance_record.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_attendance_record.state
     *
     * @param state the value for cm_attendance_record.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_attendance_record.attendance_id
     *
     * @return the value of cm_attendance_record.attendance_id
     *
     * @mbg.generated
     */
    public Long getAttendanceId() {
        return attendanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_attendance_record.attendance_id
     *
     * @param attendanceId the value for cm_attendance_record.attendance_id
     *
     * @mbg.generated
     */
    public void setAttendanceId(Long attendanceId) {
        this.attendanceId = attendanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_attendance_record
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", signTime=").append(signTime);
        sb.append(", departmentId=").append(departmentId);
        sb.append(", userName=").append(userName);
        sb.append(", state=").append(state);
        sb.append(", attendanceId=").append(attendanceId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}