package mess.wkb.cm.code.vo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cm_attendance
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CmAttendance implements Serializable {
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column cm_attendance.id
    *
    * @mbg.generated
    */
   private Long id;

   /**
    * Database Column Remarks:
    *   签到事件名称
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column cm_attendance.name
    *
    * @mbg.generated
    */
   private String name;

   /**
    * Database Column Remarks:
    *   内容
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column cm_attendance.content
    *
    * @mbg.generated
    */
   private String content;

   /**
    * Database Column Remarks:
    *   地点
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column cm_attendance.place
    *
    * @mbg.generated
    */
   private String place;

   /**
    * Database Column Remarks:
    *   签到创建时间
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column cm_attendance.creat_time
    *
    * @mbg.generated
    */
   private Date creatTime;

   /**
    * Database Column Remarks:
    *   签到开始时间
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column cm_attendance.begin_time
    *
    * @mbg.generated
    */
   private Date beginTime;

   /**
    * Database Column Remarks:
    *   签到结束时间
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column cm_attendance.end_time
    *
    * @mbg.generated
    */
   private Date endTime;

   /**
    * Database Column Remarks:
    *   所属部门
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column cm_attendance.department_id
    *
    * @mbg.generated
    */
   private String departmentId;

   /**
    * Database Column Remarks:
    *   发起人
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column cm_attendance.user_name
    *
    * @mbg.generated
    */
   private String userName;

   /**
    * Database Column Remarks:
    *   状态
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column cm_attendance.state
    *
    * @mbg.generated
    */
   private String state;

   /**
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database table cm_attendance
    *
    * @mbg.generated
    */
   private static final long serialVersionUID = 1L;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column cm_attendance.id
    *
    * @return the value of cm_attendance.id
    *
    * @mbg.generated
    */
   public Long getId() {
       return id;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column cm_attendance.id
    *
    * @param id the value for cm_attendance.id
    *
    * @mbg.generated
    */
   public void setId(Long id) {
       this.id = id;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column cm_attendance.name
    *
    * @return the value of cm_attendance.name
    *
    * @mbg.generated
    */
   public String getName() {
       return name;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column cm_attendance.name
    *
    * @param name the value for cm_attendance.name
    *
    * @mbg.generated
    */
   public void setName(String name) {
       this.name = name == null ? null : name.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column cm_attendance.content
    *
    * @return the value of cm_attendance.content
    *
    * @mbg.generated
    */
   public String getContent() {
       return content;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column cm_attendance.content
    *
    * @param content the value for cm_attendance.content
    *
    * @mbg.generated
    */
   public void setContent(String content) {
       this.content = content == null ? null : content.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column cm_attendance.place
    *
    * @return the value of cm_attendance.place
    *
    * @mbg.generated
    */
   public String getPlace() {
       return place;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column cm_attendance.place
    *
    * @param place the value for cm_attendance.place
    *
    * @mbg.generated
    */
   public void setPlace(String place) {
       this.place = place == null ? null : place.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column cm_attendance.creat_time
    *
    * @return the value of cm_attendance.creat_time
    *
    * @mbg.generated
    */
   public Date getCreatTime() {
       return creatTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column cm_attendance.creat_time
    *
    * @param creatTime the value for cm_attendance.creat_time
    *
    * @mbg.generated
    */
   public void setCreatTime(Date creatTime) {
       this.creatTime = creatTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column cm_attendance.begin_time
    *
    * @return the value of cm_attendance.begin_time
    *
    * @mbg.generated
    */
   public Date getBeginTime() {
       return beginTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column cm_attendance.begin_time
    *
    * @param beginTime the value for cm_attendance.begin_time
    *
    * @mbg.generated
    */
   public void setBeginTime(Date beginTime) {
       this.beginTime = beginTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column cm_attendance.end_time
    *
    * @return the value of cm_attendance.end_time
    *
    * @mbg.generated
    */
   public Date getEndTime() {
       return endTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column cm_attendance.end_time
    *
    * @param endTime the value for cm_attendance.end_time
    *
    * @mbg.generated
    */
   public void setEndTime(Date endTime) {
       this.endTime = endTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column cm_attendance.department_id
    *
    * @return the value of cm_attendance.department_id
    *
    * @mbg.generated
    */
   public String getDepartmentId() {
       return departmentId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column cm_attendance.department_id
    *
    * @param departmentId the value for cm_attendance.department_id
    *
    * @mbg.generated
    */
   public void setDepartmentId(String departmentId) {
       this.departmentId = departmentId == null ? null : departmentId.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column cm_attendance.user_name
    *
    * @return the value of cm_attendance.user_name
    *
    * @mbg.generated
    */
   public String getUserName() {
       return userName;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column cm_attendance.user_name
    *
    * @param userName the value for cm_attendance.user_name
    *
    * @mbg.generated
    */
   public void setUserName(String userName) {
       this.userName = userName == null ? null : userName.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column cm_attendance.state
    *
    * @return the value of cm_attendance.state
    *
    * @mbg.generated
    */
   public String getState() {
       return state;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column cm_attendance.state
    *
    * @param state the value for cm_attendance.state
    *
    * @mbg.generated
    */
   public void setState(String state) {
       this.state = state == null ? null : state.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table cm_attendance
    *
    * @mbg.generated
    */
   @Override
   public String toString() {
       StringBuilder sb = new StringBuilder();
       sb.append(getClass().getSimpleName());
       sb.append(" [");
       sb.append("Hash = ").append(hashCode());
       sb.append(", id=").append(id);
       sb.append(", name=").append(name);
       sb.append(", content=").append(content);
       sb.append(", place=").append(place);
       sb.append(", creatTime=").append(creatTime);
       sb.append(", beginTime=").append(beginTime);
       sb.append(", endTime=").append(endTime);
       sb.append(", departmentId=").append(departmentId);
       sb.append(", userName=").append(userName);
       sb.append(", state=").append(state);
       sb.append(", serialVersionUID=").append(serialVersionUID);
       sb.append("]");
       return sb.toString();
   }
}