package mess.wkb.cm.code.vo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cm_payment_record
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CmPaymentRecord implements Serializable {
    /**
     *
     */
    private Long id;

    /**
     *   付款时间
     */
    private Date payTime;

    /**
     *   所属部门
     */
    private String departmentId;

    /**
     *   发起人
     */
    private String userName;

    /**
     *   状态
     */
    private String state;

    /**
     *   活动id
     */
    private Long paymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cm_payment_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_payment_record.id
     *
     * @return the value of cm_payment_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_payment_record.id
     *
     * @param id the value for cm_payment_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_payment_record.pay_time
     *
     * @return the value of cm_payment_record.pay_time
     *
     * @mbg.generated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_payment_record.pay_time
     *
     * @param payTime the value for cm_payment_record.pay_time
     *
     * @mbg.generated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_payment_record.department_id
     *
     * @return the value of cm_payment_record.department_id
     *
     * @mbg.generated
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_payment_record.department_id
     *
     * @param departmentId the value for cm_payment_record.department_id
     *
     * @mbg.generated
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_payment_record.user_name
     *
     * @return the value of cm_payment_record.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_payment_record.user_name
     *
     * @param userName the value for cm_payment_record.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_payment_record.state
     *
     * @return the value of cm_payment_record.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_payment_record.state
     *
     * @param state the value for cm_payment_record.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_payment_record.payment_id
     *
     * @return the value of cm_payment_record.payment_id
     *
     * @mbg.generated
     */
    public Long getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_payment_record.payment_id
     *
     * @param paymentId the value for cm_payment_record.payment_id
     *
     * @mbg.generated
     */
    public void setPaymentId(Long paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_payment_record
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", payTime=").append(payTime);
        sb.append(", departmentId=").append(departmentId);
        sb.append(", userName=").append(userName);
        sb.append(", state=").append(state);
        sb.append(", paymentId=").append(paymentId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}