package mess.wkb.cm.code.vo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cm_payment
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CmPayment implements Serializable {
    /**
     *
     */
    private Long id;

    /**
     *   缴费原因
     */
    private String name;

    /**
     *   缴费创建时间
     */
    private Date creatTime;

    /**
     *   所属部门
     */
    private String departmentId;

    /**
     *   发起人
     */
    private String userName;

    /**
     *   状态
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cm_payment
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_payment.id
     *
     * @return the value of cm_payment.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_payment.id
     *
     * @param id the value for cm_payment.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_payment.name
     *
     * @return the value of cm_payment.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_payment.name
     *
     * @param name the value for cm_payment.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_payment.creat_time
     *
     * @return the value of cm_payment.creat_time
     *
     * @mbg.generated
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_payment.creat_time
     *
     * @param creatTime the value for cm_payment.creat_time
     *
     * @mbg.generated
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_payment.department_id
     *
     * @return the value of cm_payment.department_id
     *
     * @mbg.generated
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_payment.department_id
     *
     * @param departmentId the value for cm_payment.department_id
     *
     * @mbg.generated
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_payment.user_name
     *
     * @return the value of cm_payment.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_payment.user_name
     *
     * @param userName the value for cm_payment.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_payment.state
     *
     * @return the value of cm_payment.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_payment.state
     *
     * @param state the value for cm_payment.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_payment
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", creatTime=").append(creatTime);
        sb.append(", departmentId=").append(departmentId);
        sb.append(", userName=").append(userName);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}