package mess.wkb.cm.code.vo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cm_power
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CmPower implements Serializable {
    /**
     *
     */
    private String id;

    /**
     *   权限名称
     */
    private String name;

    /**
     *   上一级权限
     */
    private String parentId;

    /**
     *   内容
     */
    private String content;

    /**
     *   权限类型
     */
    private String soft;

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_power.id
     *
     * @return the value of cm_power.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_power.id
     *
     * @param id the value for cm_power.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_power.name
     *
     * @return the value of cm_power.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_power.name
     *
     * @param name the value for cm_power.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_power.parent_id
     *
     * @return the value of cm_power.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_power.parent_id
     *
     * @param parentId the value for cm_power.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_power.content
     *
     * @return the value of cm_power.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_power.content
     *
     * @param content the value for cm_power.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_power.soft
     *
     * @return the value of cm_power.soft
     *
     * @mbg.generated
     */
    public String getSoft() {
        return soft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_power.soft
     *
     * @param soft the value for cm_power.soft
     *
     * @mbg.generated
     */
    public void setSoft(String soft) {
        this.soft = soft == null ? null : soft.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_power
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", parentId=").append(parentId);
        sb.append(", content=").append(content);
        sb.append(", soft=").append(soft);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}